export interface ProxyClientOptions {
  /**
   * Route filtering behavior for inbound server paths.
   * - "inclusive": proxy everything except `routes`
   * - "exclusive": proxy only `routes`
   */
  mode?: "inclusive" | "exclusive";
  /**
   * Path rules used with `mode`, for example `["/health", "/metrics"]`.
   * Query params are ignored; matching is based on path only.
   */
  routes?: string[];
  /**
   * Path matcher behavior for `routes`.
   * - false (default): exact path only (`/route` does not match `/route/subroute`)
   * - true: include subroutes (`/route` matches `/route/*`)
   */
  matchSubroutes?: boolean;
  /**
   * Interception strategy.
   * - "auto": globally intercepts `fetch` for route-matched request scope
   * - "manual": does not intercept global `fetch`; use `req.consensus.fetch` / `request`
   */
  strategy?: "auto" | "manual";
  /**
   * Cache time-to-live in seconds for proxy responses.
   * Sent as `x-cache-ttl`; controls how long deduped responses can be reused.
   */
  cache_ttl?: number;
  /**
   * Enables verbose proxy response payload.
   * When true, proxy responses include `meta` with fields like:
   * `cached`, `dedupe_key`, `processing_ms`, and `timestamp`.
   */
  verbose?: boolean;
  /**
   * Preferred proxy region, for example `"us-east"`.
   * Sent as `x-node-region`.
   */
  node_region?: string;
  /**
   * Force routing through a specific node domain, for example:
   * `"nodexyz.consensus.canister.software"`.
   * Sent as `x-node-domain`.
   */
  node_domain?: string;
  /**
   * Exclude a specific node/domain from routing.
   * Sent as `x-node-exclude`.
   */
  node_exclude?: string;
  /**
   * Max proxy spend in USD (up to 6 decimals).
   * Once exhausted, ProxyClient stands down and uses direct fetch.
   */
  limit_usd?: number;
  /** Called once when proxy budget is exhausted and stand-down activates. */
  on_limit_reached?: (budget: ProxyBudgetSnapshot) => void;
}

export interface ProxyBudgetSnapshot {
  /** Configured max spend in USD, or null when no limit is configured. */
  limit_usd: number | null;
  /** Fixed server proxy charge per paid request. */
  request_cost_usd: number;
  /** Total spent so far in USD. */
  spent_usd: number;
  /** Remaining budget in USD, or null when unlimited. */
  remaining_usd: number | null;
  /** True when budget guard has disabled further proxying. */
  exhausted: boolean;
}

export interface ProxyResponseShape {
  /** HTTP status code returned by proxy response. */
  status: number;
  /** HTTP reason phrase from proxy response. */
  statusText: string;
  /** Response headers from the target/proxy response. */
  headers: Record<string, string>;
  /** Parsed payload body (JSON/object/string) returned by proxy. */
  data: unknown;
  /**
   * Verbose metadata returned when `verbose` is enabled.
   * Common fields:
   * - `cached`: whether response came from proxy cache
   * - `dedupe_key`: deduplication key used by proxy
   * - `processing_ms`: end-to-end proxy processing duration
   * - `timestamp`: ISO timestamp generated by proxy
   */
  meta: {
    cached?: boolean;
    dedupe_key?: string;
    processing_ms?: number;
    timestamp?: string;
    [key: string]: unknown;
  } | null;
}

export interface ProxyClientRequestContext {
  consensus?: {
    strategy?: "auto" | "manual";
    shouldProxy?: boolean;
    fetch?: (
      input: RequestInfo | URL,
      init?: RequestInit,
      perRequestOptions?: Partial<ProxyClientOptions>
    ) => Promise<Response>;
    request?: (
      payload: {
        target_url?: string;
        method?: string;
        headers?: Record<string, string>;
        body?: unknown;
      },
      perRequestOptions?: Partial<ProxyClientOptions>
    ) => Promise<ProxyResponseShape>;
    passthroughFetch?: ((input: RequestInfo | URL, init?: RequestInit) => Promise<Response>) | null;
    createFetch?: (pathname?: string) => (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
    getBudget?: () => ProxyBudgetSnapshot;
    isStandDown?: () => boolean;
  };
  [key: string]: unknown;
}

export interface ProxyClientRuntime {
  fetch(
    input: RequestInfo | URL,
    init?: RequestInit,
    perRequestOptions?: Partial<ProxyClientOptions>
  ): Promise<Response>;
  request(
    payload: {
      target_url?: string;
      method?: string;
      headers?: Record<string, string>;
      body?: unknown;
    },
    perRequestOptions?: Partial<ProxyClientOptions>
  ): Promise<ProxyResponseShape>;
  runWithPath<T>(pathname: string, run: () => T | Promise<T>): Promise<T>;
  createFetch(pathname?: string): (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
  getBudget(): ProxyBudgetSnapshot;
  resetBudget(): void;
  isStandDown(): boolean;
}

export type ProxyClientMiddleware = ((
  req: ProxyClientRequestContext,
  res: unknown,
  next: (err?: unknown) => void
) => void) &
  ProxyClientRuntime;

export declare function ProxyClient(
  fetchWithPayment: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
  options?: ProxyClientOptions
): ProxyClientMiddleware;

export type ConsensusSocketModel = "hybrid" | "time" | "data";

export interface ConsensusSocketTokenParams {
  /** Billing model for session pricing. */
  model?: ConsensusSocketModel;
  /** Session duration to purchase (integer minutes, >= 0). */
  minutes?: number;
  /** Session data amount to purchase (integer MB, >= 0). */
  megabytes?: number;
  /** Optional preferred node region for token/session routing (e.g. `"us-east"`). */
  nodeRegion?: string;
  /** Optional hard route to a specific node domain (e.g. `"nodexyz.consensus.canister.software"`). */
  nodeDomain?: string;
  /** Optional node/domain to exclude from routing. */
  nodeExclude?: string;
}

export interface ConsensusSocketTokenAuth {
  token: string;
  connect_url: string;
  expires_in: number;
}

export interface ConsensusSocketConnectTarget {
  connect_url: string;
  token?: string;
  expires_in?: number;
}

export interface ConsensusSocketCallbacks {
  onOpen?: () => void;
  onMessage?: (data: unknown) => void;
  onClose?: (event?: unknown) => void;
  onError?: (error: unknown) => void;
}

export interface ConsensusSocketSafeResult<T> {
  ok: boolean;
  data?: T;
  error?: unknown;
}

export interface ConsensusSocketSessionState {
  connected: boolean;
  reconnecting: boolean;
  closedByCaller: boolean;
}

export interface ConsensusSocketSession {
  send(data: string | ArrayBufferLike | Blob | ArrayBufferView): void;
  close(code?: number, reason?: string): void;
  on(event: "open" | "message" | "close" | "error", handler: (...args: unknown[]) => void): void;
  off(event: "open" | "message" | "close" | "error", handler: (...args: unknown[]) => void): void;
  getState(): ConsensusSocketSessionState;
}

export interface ConsensusSocketClientOptions {
  /** Custom WebSocket constructor; auto-detected when omitted. */
  webSocketFactory?: new (...args: unknown[]) => unknown;
  /** Max time to wait for websocket open before failing (ms). */
  openTimeoutMs?: number;
  /** Fixed reconnect delay (ms). */
  reconnectIntervalMs?: number;
  /** Default token params merged into each requestToken call. */
  defaults?: ConsensusSocketTokenParams;
  /** Max websocket spend in USD (up to 6 decimals) before token requests are blocked. */
  limit_usd?: number;
  /** Called once when websocket budget is exhausted. */
  on_limit_reached?: (budget: ConsensusSocketBudgetSnapshot) => void;
}

export interface ConsensusSocketBudgetSnapshot {
  /** Configured max spend in USD, or null when no limit is configured. */
  limit_usd: number | null;
  /** Total spent so far in USD. */
  spent_usd: number;
  /** Remaining budget in USD, or null when unlimited. */
  remaining_usd: number | null;
  /** True when budget guard blocks further token purchases. */
  exhausted: boolean;
  /** Last locally quoted token/session price in USD. */
  last_quote_usd: number;
}

export interface ConsensusSocketClient {
  requestToken(
    params?: ConsensusSocketTokenParams,
    options?: { safe?: false }
  ): Promise<ConsensusSocketTokenAuth>;
  requestToken(
    params: ConsensusSocketTokenParams | undefined,
    options: { safe: true }
  ): Promise<ConsensusSocketSafeResult<ConsensusSocketTokenAuth>>;
  connect(
    connectUrlOrAuth: string | ConsensusSocketConnectTarget,
    callbacks?: ConsensusSocketCallbacks,
    options?: { safe?: false }
  ): Promise<ConsensusSocketSession>;
  connect(
    connectUrlOrAuth: string | ConsensusSocketConnectTarget,
    callbacks: ConsensusSocketCallbacks | undefined,
    options: { safe: true }
  ): Promise<ConsensusSocketSafeResult<ConsensusSocketSession>>;
  getBudget(): ConsensusSocketBudgetSnapshot;
  resetBudget(): void;
  isStandDown(): boolean;
}

export declare function SocketClient(
  fetchWithPayment: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
  options?: ConsensusSocketClientOptions
): ConsensusSocketClient;
